"""create_housing_units

Revision ID: 39c99893cbde
Revises: 
Create Date: 2026-04-21 04:59:28.891417

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c99893cbde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_units',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('building_id', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('borough', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('construction_type', sa.String(), nullable=True),
    sa.Column('num_units', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_units >= 0', name='ck_housing_units_num_units_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'building_id', name='uq_housing_units_project_building')
    )
    op.create_index('ix_housing_units_borough', 'housing_units', ['borough'], unique=False)
    op.create_index('ix_housing_units_construction_type', 'housing_units', ['construction_type'], unique=False)
    op.create_index('ix_housing_units_postcode', 'housing_units', ['postcode'], unique=False)
    op.create_index('ix_housing_units_street_name', 'housing_units', ['street_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_housing_units_street_name', table_name='housing_units')
    op.drop_index('ix_housing_units_postcode', table_name='housing_units')
    op.drop_index('ix_housing_units_construction_type', table_name='housing_units')
    op.drop_index('ix_housing_units_borough', table_name='housing_units')
    op.drop_table('housing_units')
    # ### end Alembic commands ###
